# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: "Create GitHub Release"
description: "Creates GitHub releases"
inputs:
  type:
    description: "Type of the release"
    required: true
  token:
    description: "GitHub access token"
    required: true
  files:
    description: "Newline-separated list of the files to upload"
    required: false
runs:
  using: "node16"
  main: ./bootstrap.cjs
