-- luacheck: ignore 111

--[[--
Barotrauma Submarine class with some additional functions and fields

Barotrauma source code: [Submarine.cs](https://github.com/evilfactory/Barotrauma-lua-attempt/blob/master/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs)

Not all fields and methods will work, this doc was autogenerated.
]]
-- @code Submarine
-- @pragma nostrip

local Submarine = {}