name: Generate Docs - Cs

on:
  workflow_run:
    workflows: ["Clean Docs"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Create directories
        run: mkdir -p doxygen/build ; mkdir -p doxygen/build/baro-server ; mkdir -p doxygen/build/baro-client

      - name: Build server documentation
        uses: mattnotmitt/doxygen-action@v1.9.1
        with:
          working-directory: 'doxygen/baro-server'
          doxyfile-path: './Doxyfile'

      - name: Build client documentation
        uses: mattnotmitt/doxygen-action@v1.9.1
        with:
          working-directory: 'doxygen/baro-client'
          doxyfile-path: './Doxyfile'

      - name: Build containing documentation
        uses: mattnotmitt/doxygen-action@v1.9.1
        with:
          working-directory: 'doxygen/'
          doxyfile-path: './Doxyfile'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doxygen/build
          destination_dir: cs-docs
          keep_files: true
