# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: On push to a secondary branch

on:
  push:
    branches-ignore: [master]

jobs:
  harden-ci-security:
    uses: ./.github/workflows/harden-ci-security.yml
    with:
      ref: ${{ github.event.ref }}

  run-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      ref: ${{ github.event.ref }}
