# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Report test results

# HACK: the "on-push-pr" workflow gets run with read-only perms.
# This workflow will run in our repo with write permissions after
# the PR checks are done running.
on:
  workflow_run:
    workflows:
      - On push to master branch
      - On push to a secondary branch
      - On push to a PR
    types: [completed]

jobs:
  report-test-results:
    runs-on: ubuntu-latest
    steps:
      - name: Report test results
        uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226 # v1.6.0
        with:
          name: Test results
          artifact: test-results
          path: test-results.trx
          fail-on-error: false
          reporter: dotnet-trx
